import type { AssetType } from '../../shared/types';

export const ASSET_TYPES: AssetType[] = [
  {
    code: 'SCRIPT',
    name_cn: '剧本',
    icon: '📝',
    folder_path: '02_Data/Script',
    filename_tpl: '{series}_{content}_SCRIPT',
    file_exts: ['.docx', '.md', '.txt'],
    storage_ext: '.md',
    storage_backend: 'github',
    parent_panel: 'SCRIPT',
    needs_before: [],
    supports_paste: true,
    allow_ai_generate: false,
    sort_order: 10,
    enabled: true,
  },
  {
    code: 'PROMPT_IMG',
    name_cn: '分镜图提示词',
    icon: '🖼️',
    folder_path: '02_Data/Prompt/Image',
    filename_tpl: '{content}_PROMPT_IMG_{number:03}_v{version:03}',
    file_exts: ['.xlsx', '.md', '.txt'],
    storage_ext: '.md',
    storage_backend: 'github',
    parent_panel: 'PROMPT',
    needs_before: ['SCRIPT'],
    supports_paste: true,
    allow_ai_generate: false,
    sort_order: 20,
    enabled: true,
  },
  {
    code: 'PROMPT_VID',
    name_cn: '分镜视频提示词',
    icon: '🎞️',
    folder_path: '02_Data/Prompt/Video',
    filename_tpl: '{content}_PROMPT_VID_{number:03}_v{version:03}',
    file_exts: ['.xlsx', '.md', '.txt'],
    storage_ext: '.md',
    storage_backend: 'github',
    parent_panel: 'PROMPT',
    needs_before: ['SCRIPT'],
    supports_paste: true,
    allow_ai_generate: false,
    sort_order: 21,
    enabled: true,
  },
  {
    code: 'SHOT_IMG',
    name_cn: '分镜图',
    icon: '🖼️',
    folder_path: '02_Data/Shot/{episode}/Images',
    filename_tpl: '{content}_SHOT_{number:03}_v{version:03}',
    file_exts: ['.png', '.jpg', '.jpeg', '.webp'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'SHOT',
    needs_before: ['PROMPT_IMG'],
    supports_paste: false,
    allow_ai_generate: true,
    sort_order: 22,
    enabled: true,
  },
  {
    code: 'SHOT_VID',
    name_cn: '分镜视频',
    icon: '🎬',
    folder_path: '02_Data/Shot/{episode}/Videos',
    filename_tpl: '{content}_SHOT_{number:03}_v{version:03}',
    file_exts: ['.mp4', '.mov', '.webm'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'SHOT',
    needs_before: ['SHOT_IMG'],
    supports_paste: false,
    allow_ai_generate: true,
    sort_order: 23,
    enabled: true,
  },
  {
    code: 'CHAR',
    name_cn: '角色',
    icon: '👤',
    folder_path: '02_Data/Assets/Characters',
    filename_tpl: '{content}_CHAR_{name}_{variant}_v{version:03}',
    file_exts: ['.png', '.jpg', '.jpeg', '.webp'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'ASSET',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: true,
    sort_order: 30,
    enabled: true,
  },
  {
    code: 'PROP',
    name_cn: '道具',
    icon: '🎒',
    folder_path: '02_Data/Assets/Props',
    filename_tpl: '{content}_PROP_{name}_{variant}_v{version:03}',
    file_exts: ['.png', '.jpg', '.jpeg', '.webp'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'ASSET',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: true,
    sort_order: 31,
    enabled: true,
  },
  {
    code: 'SCENE',
    name_cn: '场景',
    icon: '🏞️',
    folder_path: '02_Data/Assets/Scenes',
    filename_tpl: '{content}_SCENE_{name}_{variant}_v{version:03}',
    file_exts: ['.png', '.jpg', '.jpeg', '.webp'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'ASSET',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: true,
    sort_order: 32,
    enabled: true,
  },
  {
    code: 'DIALOG',
    name_cn: '对白',
    icon: '💬',
    folder_path: '02_Data/Audio/Dialog',
    filename_tpl: '{content}_DIALOG_{language}_v{version:03}',
    file_exts: ['.wav', '.mp3'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'AUDIO',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: false,
    sort_order: 40,
    enabled: false,
  },
  {
    code: 'BGM',
    name_cn: '配乐',
    icon: '🎵',
    folder_path: '02_Data/Audio/BGM',
    filename_tpl: '{content}_BGM_{name}_v{version:03}',
    file_exts: ['.wav', '.mp3'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'AUDIO',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: false,
    sort_order: 41,
    enabled: false,
  },
  {
    code: 'SONG',
    name_cn: '歌曲',
    icon: '🎤',
    folder_path: '02_Data/Audio/Song',
    filename_tpl: '{content}_SONG_{name}_v{version:03}',
    file_exts: ['.wav', '.mp3'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'AUDIO',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: false,
    sort_order: 42,
    enabled: false,
  },
  {
    code: 'SFX',
    name_cn: '音效',
    icon: '🔊',
    folder_path: '02_Data/Audio/SFX',
    filename_tpl: '{content}_SFX_{name}_v{version:03}',
    file_exts: ['.wav', '.mp3'],
    storage_ext: 'keep_as_is',
    storage_backend: 'r2',
    parent_panel: 'AUDIO',
    needs_before: [],
    supports_paste: false,
    allow_ai_generate: false,
    sort_order: 43,
    enabled: false,
  },
];

export function getAssetType(code: string): AssetType | undefined {
  return ASSET_TYPES.find((type) => type.code === code);
}
